-- Inserir todos os tribunais do Brasil
INSERT INTO public.tribunais (codigo, nome, tipo, url_base, api_disponivel, ativo) VALUES
-- Tribunais de Justiça Estaduais
('TJAC', 'Tribunal de Justiça do Acre', 'estadual', 'https://esaj.tjac.jus.br', false, true),
('TJAL', 'Tribunal de Justiça de Alagoas', 'estadual', 'https://www2.tjal.jus.br', false, true),
('TJAP', 'Tribunal de Justiça do Amapá', 'estadual', 'https://www.tjap.jus.br', false, true),
('TJAM', 'Tribunal de Justiça do Amazonas', 'estadual', 'https://consultasaj.tjam.jus.br', false, true),
('TJBA', 'Tribunal de Justiça da Bahia', 'estadual', 'https://esaj.tjba.jus.br', false, true),
('TJCE', 'Tribunal de Justiça do Ceará', 'estadual', 'https://esaj.tjce.jus.br', false, true),
('TJDF', 'Tribunal de Justiça do Distrito Federal', 'estadual', 'https://pje.tjdft.jus.br', false, true),
('TJES', 'Tribunal de Justiça do Espírito Santo', 'estadual', 'https://sistemas.tjes.jus.br', false, true),
('TJGO', 'Tribunal de Justiça de Goiás', 'estadual', 'https://projudi.tjgo.jus.br', false, true),
('TJMA', 'Tribunal de Justiça do Maranhão', 'estadual', 'https://www.tjma.jus.br', false, true),
('TJMT', 'Tribunal de Justiça de Mato Grosso', 'estadual', 'https://pje.tjmt.jus.br', false, true),
('TJMS', 'Tribunal de Justiça de Mato Grosso do Sul', 'estadual', 'https://esaj.tjms.jus.br', false, true),
('TJMG', 'Tribunal de Justiça de Minas Gerais', 'estadual', 'https://pje-consulta-publica.tjmg.jus.br', false, true),
('TJPA', 'Tribunal de Justiça do Pará', 'estadual', 'https://pje.tjpa.jus.br', false, true),
('TJPB', 'Tribunal de Justiça da Paraíba', 'estadual', 'https://pje.tjpb.jus.br', false, true),
('TJPR', 'Tribunal de Justiça do Paraná', 'estadual', 'https://portal.tjpr.jus.br', false, true),
('TJPE', 'Tribunal de Justiça de Pernambuco', 'estadual', 'https://www.tjpe.jus.br', false, true),
('TJPI', 'Tribunal de Justiça do Piauí', 'estadual', 'https://pje.tjpi.jus.br', false, true),
('TJRJ', 'Tribunal de Justiça do Rio de Janeiro', 'estadual', 'https://www4.tjrj.jus.br', false, true),
('TJRN', 'Tribunal de Justiça do Rio Grande do Norte', 'estadual', 'https://pje.tjrn.jus.br', false, true),
('TJRS', 'Tribunal de Justiça do Rio Grande do Sul', 'estadual', 'https://www.tjrs.jus.br', false, true),
('TJRO', 'Tribunal de Justiça de Rondônia', 'estadual', 'https://pje.tjro.jus.br', false, true),
('TJRR', 'Tribunal de Justiça de Roraima', 'estadual', 'https://pje.tjrr.jus.br', false, true),
('TJSC', 'Tribunal de Justiça de Santa Catarina', 'estadual', 'https://esaj.tjsc.jus.br', false, true),
('TJSP', 'Tribunal de Justiça de São Paulo', 'estadual', 'https://esaj.tjsp.jus.br', false, true),
('TJSE', 'Tribunal de Justiça de Sergipe', 'estadual', 'https://pje.tjse.jus.br', false, true),
('TJTO', 'Tribunal de Justiça do Tocantins', 'estadual', 'https://wwa.tjto.jus.br', false, true),

-- Tribunais Regionais Federais
('TRF1', 'Tribunal Regional Federal da 1ª Região', 'federal', 'https://pje.trf1.jus.br', false, true),
('TRF2', 'Tribunal Regional Federal da 2ª Região', 'federal', 'https://pje.trf2.jus.br', false, true),
('TRF3', 'Tribunal Regional Federal da 3ª Região', 'federal', 'https://pje.trf3.jus.br', false, true),
('TRF4', 'Tribunal Regional Federal da 4ª Região', 'federal', 'https://pje.trf4.jus.br', false, true),
('TRF5', 'Tribunal Regional Federal da 5ª Região', 'federal', 'https://pje.trf5.jus.br', false, true),
('TRF6', 'Tribunal Regional Federal da 6ª Região', 'federal', 'https://pje.trf6.jus.br', false, true),

-- Tribunais Regionais do Trabalho (principais)
('TRT1', 'Tribunal Regional do Trabalho da 1ª Região (RJ)', 'trabalhista', 'https://pje.trt1.jus.br', false, true),
('TRT2', 'Tribunal Regional do Trabalho da 2ª Região (SP)', 'trabalhista', 'https://pje.trt2.jus.br', false, true),
('TRT3', 'Tribunal Regional do Trabalho da 3ª Região (MG)', 'trabalhista', 'https://pje.trt3.jus.br', false, true),
('TRT4', 'Tribunal Regional do Trabalho da 4ª Região (RS)', 'trabalhista', 'https://pje.trt4.jus.br', false, true),
('TRT5', 'Tribunal Regional do Trabalho da 5ª Região (BA)', 'trabalhista', 'https://pje.trt5.jus.br', false, true),
('TRT6', 'Tribunal Regional do Trabalho da 6ª Região (PE)', 'trabalhista', 'https://pje.trt6.jus.br', false, true),
('TRT7', 'Tribunal Regional do Trabalho da 7ª Região (CE)', 'trabalhista', 'https://pje.trt7.jus.br', false, true),
('TRT8', 'Tribunal Regional do Trabalho da 8ª Região (PA/AP)', 'trabalhista', 'https://pje.trt8.jus.br', false, true),
('TRT9', 'Tribunal Regional do Trabalho da 9ª Região (PR)', 'trabalhista', 'https://pje.trt9.jus.br', false, true),
('TRT10', 'Tribunal Regional do Trabalho da 10ª Região (DF/TO)', 'trabalhista', 'https://pje.trt10.jus.br', false, true),
('TRT11', 'Tribunal Regional do Trabalho da 11ª Região (AM/RR)', 'trabalhista', 'https://pje.trt11.jus.br', false, true),
('TRT12', 'Tribunal Regional do Trabalho da 12ª Região (SC)', 'trabalhista', 'https://pje.trt12.jus.br', false, true),
('TRT13', 'Tribunal Regional do Trabalho da 13ª Região (PB)', 'trabalhista', 'https://pje.trt13.jus.br', false, true),
('TRT14', 'Tribunal Regional do Trabalho da 14ª Região (RO/AC)', 'trabalhista', 'https://pje.trt14.jus.br', false, true),
('TRT15', 'Tribunal Regional do Trabalho da 15ª Região (SP)', 'trabalhista', 'https://pje.trt15.jus.br', false, true),
('TRT16', 'Tribunal Regional do Trabalho da 16ª Região (MA)', 'trabalhista', 'https://pje.trt16.jus.br', false, true),
('TRT17', 'Tribunal Regional do Trabalho da 17ª Região (ES)', 'trabalhista', 'https://pje.trt17.jus.br', false, true),
('TRT18', 'Tribunal Regional do Trabalho da 18ª Região (GO)', 'trabalhista', 'https://pje.trt18.jus.br', false, true),
('TRT19', 'Tribunal Regional do Trabalho da 19ª Região (AL)', 'trabalhista', 'https://pje.trt19.jus.br', false, true),
('TRT20', 'Tribunal Regional do Trabalho da 20ª Região (SE)', 'trabalhista', 'https://pje.trt20.jus.br', false, true),
('TRT21', 'Tribunal Regional do Trabalho da 21ª Região (RN)', 'trabalhista', 'https://pje.trt21.jus.br', false, true),
('TRT22', 'Tribunal Regional do Trabalho da 22ª Região (PI)', 'trabalhista', 'https://pje.trt22.jus.br', false, true),
('TRT23', 'Tribunal Regional do Trabalho da 23ª Região (MT)', 'trabalhista', 'https://pje.trt23.jus.br', false, true),
('TRT24', 'Tribunal Regional do Trabalho da 24ª Região (MS)', 'trabalhista', 'https://pje.trt24.jus.br', false, true),

-- Tribunais Regionais Eleitorais (principais)
('TREAC', 'Tribunal Regional Eleitoral do Acre', 'eleitoral', 'https://www.tre-ac.jus.br', false, true),
('TREAL', 'Tribunal Regional Eleitoral de Alagoas', 'eleitoral', 'https://www.tre-al.jus.br', false, true),
('TREAP', 'Tribunal Regional Eleitoral do Amapá', 'eleitoral', 'https://www.tre-ap.jus.br', false, true),
('TREAM', 'Tribunal Regional Eleitoral do Amazonas', 'eleitoral', 'https://www.tre-am.jus.br', false, true),
('TREBA', 'Tribunal Regional Eleitoral da Bahia', 'eleitoral', 'https://www.tre-ba.jus.br', false, true),
('TRECE', 'Tribunal Regional Eleitoral do Ceará', 'eleitoral', 'https://www.tre-ce.jus.br', false, true),
('TREDF', 'Tribunal Regional Eleitoral do Distrito Federal', 'eleitoral', 'https://www.tre-df.jus.br', false, true),
('TREES', 'Tribunal Regional Eleitoral do Espírito Santo', 'eleitoral', 'https://www.tre-es.jus.br', false, true),
('TREGO', 'Tribunal Regional Eleitoral de Goiás', 'eleitoral', 'https://www.tre-go.jus.br', false, true),
('TREMA', 'Tribunal Regional Eleitoral do Maranhão', 'eleitoral', 'https://www.tre-ma.jus.br', false, true),
('TREMG', 'Tribunal Regional Eleitoral de Minas Gerais', 'eleitoral', 'https://www.tre-mg.jus.br', false, true),
('TREMS', 'Tribunal Regional Eleitoral de Mato Grosso do Sul', 'eleitoral', 'https://www.tre-ms.jus.br', false, true),
('TREMT', 'Tribunal Regional Eleitoral de Mato Grosso', 'eleitoral', 'https://www.tre-mt.jus.br', false, true),
('TREPA', 'Tribunal Regional Eleitoral do Pará', 'eleitoral', 'https://www.tre-pa.jus.br', false, true),
('TREPB', 'Tribunal Regional Eleitoral da Paraíba', 'eleitoral', 'https://www.tre-pb.jus.br', false, true),
('TREPE', 'Tribunal Regional Eleitoral de Pernambuco', 'eleitoral', 'https://www.tre-pe.jus.br', false, true),
('TREPI', 'Tribunal Regional Eleitoral do Piauí', 'eleitoral', 'https://www.tre-pi.jus.br', false, true),
('TREPR', 'Tribunal Regional Eleitoral do Paraná', 'eleitoral', 'https://www.tre-pr.jus.br', false, true),
('TRERJ', 'Tribunal Regional Eleitoral do Rio de Janeiro', 'eleitoral', 'https://www.tre-rj.jus.br', false, true),
('TRERN', 'Tribunal Regional Eleitoral do Rio Grande do Norte', 'eleitoral', 'https://www.tre-rn.jus.br', false, true),
('TRERS', 'Tribunal Regional Eleitoral do Rio Grande do Sul', 'eleitoral', 'https://www.tre-rs.jus.br', false, true),
('TRERO', 'Tribunal Regional Eleitoral de Rondônia', 'eleitoral', 'https://www.tre-ro.jus.br', false, true),
('TRERR', 'Tribunal Regional Eleitoral de Roraima', 'eleitoral', 'https://www.tre-rr.jus.br', false, true),
('TRESC', 'Tribunal Regional Eleitoral de Santa Catarina', 'eleitoral', 'https://www.tre-sc.jus.br', false, true),
('TRESE', 'Tribunal Regional Eleitoral de Sergipe', 'eleitoral', 'https://www.tre-se.jus.br', false, true),
('TRESP', 'Tribunal Regional Eleitoral de São Paulo', 'eleitoral', 'https://www.tre-sp.jus.br', false, true),
('TRETO', 'Tribunal Regional Eleitoral do Tocantins', 'eleitoral', 'https://www.tre-to.jus.br', false, true)

ON CONFLICT (codigo) DO UPDATE SET
nome = EXCLUDED.nome,
tipo = EXCLUDED.tipo,
url_base = EXCLUDED.url_base,
api_disponivel = EXCLUDED.api_disponivel,
ativo = EXCLUDED.ativo,
updated_at = now();