// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brzpdyrfjucjliqruvwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyenBkeXJmanVjamxpcXJ1dndhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNDQ0NDQsImV4cCI6MjA3MzgyMDQ0NH0.eYWC-ioDyLvdu0uCDF9AvK-IlpAY4Vw7I_mg9JntEP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});